### ISSUE TITLE
Create a different pip package than original fork

### ISSUE THREAD

**Issue by sfsekaran** [nicorellius/json-rpc-python3#1]
The package could be named `rdo_json_rpc_python3` or something similar.

**Comment by nicorellius** [comment]
That sounds good. I'll work on it and let you know. Thanks for the suggestion.

**Comment by nicorellius** [comment]
@sfsekaran Released `rdoclient-py3`:

https://pypi.org/project/rdoclient-py3/

**Comment by sfsekaran** [comment]
Awesome!!

Sathya Sekaran

**Comment by sfsekaran** [comment]
If possible, the pypi.org page should have a link back to this github page so there's no ambiguity about who owns that package. (Ignore me if I just missed the link.)

**Comment by nicorellius** [comment]
The Project Home page links to this GitHub repo. Let me know if it doesn't work for you...

**Comment by nicorellius** [comment]
Assuming we're all good here. Closing.
