### ISSUE TITLE
Your Random.org key is still visible in Git history

### ISSUE THREAD

**Issue by stephenwade** [nicorellius/json-rpc-python3#2]
You should know that your Random.org key is still visible in the repo history, such as in 46d7259. You may want to clean this up. One option is to use [BFG] with the `--replace-text` option, then force push.

[BFG]: https://rtyley.github.io/bfg-repo-cleaner/

**Comment by nicorellius** [comment]
Yeah, that's OK... I've converted this to non-production key, and I've been in contact with the original author at RANDOM.ORG to get additional keys if needed. Thanks for the git tip, though, I will probably do this anyway since secrets should not live in repos.

**Comment by nicorellius** [comment]
This is a test key and not a production key. There are limits set up on this alpha key.
